export const items = [
  {
    rangeLimit: 180,
    description: "cost",
    totalUnits: "p",
    itemOptions: [
      {
        itemNames: [
          "potatoes",
          "carrots",
          "lettuce",
          "cabbage",
          "tomatoes",
          "broccoli",
          "mushrooms",
          "onions",
          "green peppers",
          "red peppers",
          "yellow peppers",
          "rice",
          "pasta",
        ],
        units: "kg",
        isPluralisedUnits: false,
      },
      {
        itemNames: [
          "dairy milk",
          "bottled water",
          "orange juice",
          "lemon juice",
          "pineapple juice",
          "apple juice",
          "energy drink",
          "almond milk",
        ],
        units: "L",
        isPluralisedUnits: false,
      },
      {
        itemNames: [
          "coffee beans",
          "tea leaves",
          "sugar",
          "hot chocolate",
          "salt",
          "pepper",
          "grapes",
          "cashew nuts",
          "oranges",
        ],
        units: "bag",
        isPluralisedUnits: true,
      },
    ],
  },
  {
    rangeLimit: 300,
    description: "weight",
    totalUnits: "kg",
    itemOptions: [
      {
        itemNames: [
          "TVs",
          "fridges",
          "microwaves",
          "wooden pallets",
          "solar panels",
          "glass panels",
        ],
        units: "crate",
        isPluralisedUnits: true,
      },
      {
        itemNames: [
          "crude oil",
          "natural gas",
          "chlorine gas",
          "liquid helium",
          "nitrogen gas",
          "resin",
          "ammonia",
          "sulphuric acid",
        ],
        units: "container",
        isPluralisedUnits: true,
      },
    ],
  },
];
